# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

# Wait for both unit and instrumented uploads before sending notifications
codecov:
  notify:
    after_n_builds: 2

# Define flags for unit and instrumented tests
flags:
  unit:
    after_n_builds: 1
  instrumented:
    after_n_builds: 1

comment:
  layout: "header, diff, flags, components"
  require_changes: false