import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.serialization)
    id("moneymanager.kotlin-multiplatform-convention")
    id("moneymanager.android-convention")
}

// Google Drive remote-storage backend. The Drive REST API + OAuth are spoken over the shared KMP Ktor
// client and a raw ServerSocket loopback receiver, so the provider runs identically on JVM and Android
// from a single jvmAndroidMain source set. The only platform-specific piece is opening the system
// browser for consent (BrowserLauncher), implemented in jvmMain/androidMain.
//
// buildHealth (KMP quirk): ABI project/library deps used by jvmAndroidMain must be declared as `api` on
// each real platform source set (jvmMain + androidMain); runtime-only deps live in jvmAndroidMain.
kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kotlinx.serialization.json)
            }
        }

        // JVM and Android share the entire provider, OAuth, loopback receiver and account store.
        val jvmAndroidMain =
            create("jvmAndroidMain") {
                dependsOn(commonMain.get())
                dependencies {
                    implementation(libs.kotlinx.coroutines.core)
                    implementation(libs.kotlinx.serialization.json)
                    implementation(libs.ktor.client.auth)
                    implementation(libs.ktor.client.cio)
                }
            }

        jvmMain {
            dependsOn(jvmAndroidMain)
            dependencies {
                api(libs.kotlinx.serialization.core)
                api(libs.ktor.client.core)
                api(projects.app.importfilesource.core)
                api(projects.app.remotestorage.core)
                api(projects.utils.localsettings)

                implementation(libs.ktor.http)
                implementation(libs.ktor.utils)
            }
        }

        androidMain {
            dependsOn(jvmAndroidMain)
            dependencies {
                api(libs.kotlinx.serialization.core)
                api(libs.ktor.client.core)
                api(projects.app.importfilesource.core)
                api(projects.app.remotestorage.core)
                api(projects.utils.localsettings)

                implementation(libs.ktor.http)
                implementation(libs.ktor.utils)
            }
        }

        getByName("jvmTest") {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
        }
    }
}

// --- Shipped desktop Google OAuth client (build-time injected, XOR-obfuscated) ---
// The desktop loopback flow ships a default OAuth client so users get a one-click "Sign in with
// Google" instead of bringing their own credentials.json. Android authenticates natively via GMS and
// needs no secret, so this is jvmMain-only. Values resolve from (1) env vars (CI secrets), (2) gradle
// properties, then (3) a .gitignored secrets/google-oauth.properties — else empty, so builds without
// the secret still compile and the feature reports "not configured". The values are emitted as
// per-index XOR-obfuscated byte arrays, never plain string literals, so the `GOCSPX-…` secret pattern
// never appears in the artifact and push-protection / secret scanners can't match it. Obfuscation is
// only a speed bump; the real safeguards are the Cloud project quota cap and rotating this client id.
fun resolveOAuthValue(
    envVar: String,
    gradleProp: String,
    fileKey: String,
): String {
    // Trim before the emptiness check: a trailing newline/space from a CI secret or a properties file
    // would otherwise embed an invalid credential while isConfigured still reports true.
    providers
        .environmentVariable(envVar)
        .orNull
        ?.trim()
        ?.takeIf { it.isNotEmpty() }
        ?.let { return it }
    providers
        .gradleProperty(gradleProp)
        .orNull
        ?.trim()
        ?.takeIf { it.isNotEmpty() }
        ?.let { return it }
    val secretsFile = rootDir.resolve("secrets/google-oauth.properties")
    if (secretsFile.exists()) {
        val props = Properties()
        secretsFile.inputStream().use { props.load(it) }
        props
            .getProperty(fileKey)
            ?.trim()
            ?.takeIf { it.isNotEmpty() }
            ?.let { return it }
    }
    return ""
}

fun renderGoogleOAuthDefaults(
    clientId: String,
    clientSecret: String,
): String {
    val base = 0x3B

    fun obfuscate(value: String): String =
        value
            .mapIndexed { index, ch -> "0x%02X.toByte()".format((ch.code xor ((base + index) and 0xFF)) and 0xFF) }
            .joinToString(", ")
    return buildString {
        appendLine("package com.moneymanager.remotestorage.googledrive")
        appendLine()
        appendLine("// GENERATED by the generateGoogleOAuthDefaults Gradle task — do not edit.")
        appendLine("// Shipped desktop Google OAuth client, XOR-obfuscated so the literal secret never")
        appendLine("// appears in the artifact. Obfuscation is a speed bump, not real protection.")
        appendLine("object GoogleOAuthDefaults {")
        appendLine("    private const val BASE: Int = $base")
        appendLine()
        appendLine("    private val ID: ByteArray = byteArrayOf(${obfuscate(clientId)})")
        appendLine("    private val SECRET: ByteArray = byteArrayOf(${obfuscate(clientSecret)})")
        appendLine()
        appendLine("    val isConfigured: Boolean = ID.isNotEmpty() && SECRET.isNotEmpty()")
        appendLine()
        appendLine("    val clientId: String get() = decode(ID)")
        appendLine("    val clientSecret: String get() = decode(SECRET)")
        appendLine()
        appendLine("    private fun decode(bytes: ByteArray): String {")
        appendLine("        val chars = CharArray(bytes.size)")
        appendLine("        for (index in bytes.indices) {")
        appendLine("            chars[index] = (((bytes[index].toInt() and 0xFF) xor ((BASE + index) and 0xFF)) and 0xFF).toChar()")
        appendLine("        }")
        appendLine("        return String(chars)")
        appendLine("    }")
        appendLine("}")
    }
}

// Render at configuration time so the task action captures only the (already obfuscated) source
// string — capturing the script function instead would break the configuration cache.
val generatedGoogleOAuthSource =
    renderGoogleOAuthDefaults(
        resolveOAuthValue("GOOGLE_OAUTH_CLIENT_ID", "google.oauth.clientId", "clientId"),
        resolveOAuthValue("GOOGLE_OAUTH_CLIENT_SECRET", "google.oauth.clientSecret", "clientSecret"),
    )

val generateGoogleOAuthDefaults =
    tasks.register("generateGoogleOAuthDefaults") {
        group = "build setup"
        description = "Generates the obfuscated shipped desktop Google OAuth client (GoogleOAuthDefaults.kt)."
        val outputDir = layout.buildDirectory.dir("generated/googleOAuth/jvmMain/kotlin")
        val source = generatedGoogleOAuthSource
        // The source holds only the XOR-obfuscated bytes (never the plaintext secret), so fingerprinting
        // on it re-runs the task when credentials change without leaking them into the cache.
        inputs.property("source", source)
        outputs.dir(outputDir)
        doLast {
            val pkgDir = outputDir.get().asFile.resolve("com/moneymanager/remotestorage/googledrive")
            pkgDir.mkdirs()
            pkgDir.resolve("GoogleOAuthDefaults.kt").writeText(source)
        }
    }

kotlin.sourceSets.named("jvmMain") {
    kotlin.srcDir(generateGoogleOAuthDefaults)
}
