package com.moneymanager.domain.model

/**
 * Represents the source/origin of a transfer audit entry.
 * Tracks how each change (INSERT, UPDATE, DELETE) was initiated.
 */
enum class SourceType(
    val id: Int,
) {
    /** Manual entry by user */
    MANUAL(1),

    /** Imported from CSV file */
    CSV_IMPORT(2),

    /** Generated by sample data generator */
    SAMPLE_GENERATOR(3),

    /** System-generated (e.g., seeded currencies) */
    SYSTEM(4),

    /** Imported via REST API call */
    API(5),

    /** Imported from QIF file */
    QIF_IMPORT(6),

    /** Recreated by undoing an account merge */
    MERGE_UNDO(7),
    ;

    companion object {
        fun fromName(name: String): SourceType = valueOf(name.uppercase())
    }
}
