package com.moneymanager.strategycatalog

import com.moneymanager.domain.StrategyKey
import com.moneymanager.domain.StrategyKind
import kotlinx.serialization.Serializable

/**
 * The catalog's `index.json` manifest, generated by `:tools:strategy-catalog` from the checked-in
 * `strategy-library/` folder and published to GitHub Pages next to the artifact files.
 */
@Serializable
data class CatalogManifest(
    val entries: List<CatalogEntry> = emptyList(),
)

/**
 * One downloadable artifact in the catalog.
 *
 * @property name The artifact's unique name (matches the JSON's embedded name).
 * @property kind Which [StrategyKind] the artifact is.
 * @property fileName The artifact's file name next to index.json (per StrategyFileNaming).
 * @property contentHash Canonical version-independent content hash (StrategyArtifactCodec), compared
 *   against [com.moneymanager.domain.LocalStrategyEntry.contentHash] to detect installed/update states.
 */
@Serializable
data class CatalogEntry(
    val name: String,
    val kind: StrategyKind,
    val fileName: String,
    val contentHash: String,
) {
    val key: StrategyKey get() = StrategyKey(kind, name)
}
