name: 'Gradle Run'
description: 'Sets up JDK, Gradle, and runs a Gradle command'

inputs:
  command:
    description: 'The Gradle command to run (e.g., build, lintFormat)'
    required: true
  cache-read-only:
    description: 'Whether the Gradle cache should be read-only'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Enable KVM for Android emulator hardware acceleration
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 9.2.0
        cache-read-only: ${{ inputs.cache-read-only }}

    - name: Run Gradle
      shell: bash
      run: ./gradlew ${{ inputs.command }} --no-daemon

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/build/reports/tests/**
          **/build/test-results/**
        retention-days: 7

    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: |
          **/build/reports/**
        retention-days: 7