name: 'Gradle Run'
description: 'Sets up JDK, Gradle, and runs a Gradle command'

inputs:
  command:
    description: 'The Gradle command to run (e.g., build, lintFormat)'
    required: true
  cache-read-only:
    description: 'Whether the Gradle cache should be read-only'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Gradle environment
      uses: ./.github/actions/gradle-setup
      with:
        cache-read-only: ${{ inputs.cache-read-only }}

    - name: Run Gradle
      shell: bash
      run: ./gradlew ${{ inputs.command }} --no-daemon

    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: |
          **/build/reports/**
        retention-days: 7
